import { useMemo, useState } from "react";

type Status =
  | "draft" | "owner_review" | "revision_requested" | "owner_editing" | "owner_edit_complete"
  | "owner_approved" | "narration_authorized" | "audio_generated" | "audio_review"
  | "audio_accepted_private" | "release_approved";

type Item = Readonly<{
  id: string; title: string; type: string; scripture: string; status: Status; reflection: string;
  script: string; prayer: string; journal: string; practice: string; notes: string; rights: string;
  narrationRights: boolean; versions: readonly string[]; lockedHash?: string;
}>;

const seeds: readonly Item[] = [
  { id: "quiet-trust", title: "Quiet Trust", type: "Guided audio reflection", scripture: "Psalm 46:10; Isaiah 30:15", status: "audio_accepted_private", reflection: "A written Quiet Trust package is approved for private narration review.", script: "Private narration-review script retained in the approved package.", prayer: "Lord Jesus, meet us with Your peace. Amen.", journal: "What concern can you bring to God?", practice: "Pause and pray.", notes: "Private narration accepted. Release remains closed.", rights: "Scripture quotation remains reference-only", narrationRights: false, versions: ["Version 3 — wording approved", "Version 2 — owner revision"], lockedHash: "Recorded in approved package" },
  { id: "renewal-1", title: "Renewal Day 1 — Return", type: "Guided audio reflection", scripture: "Psalm 51:10; 2 Corinthians 5:17", status: "owner_review", reflection: "Return begins with truth. We bring God neither a polished version of ourselves nor a promise that we will never struggle again. We come honestly, trusting that Christ meets those who turn toward Him with mercy.\n\nThe call to renewal is not a demand to earn our way back. In Jesus, repentance is a return to the One whose love has already made room for us. We can name what needs to change, receive His forgiveness, and begin again under His care.", script: "Welcome to Strongr Daily.\n\nToday we reflect on returning to God. Psalm 51:10 and 2 Corinthians 5:17 point us toward the mercy of God and the new life we receive in Christ.\n\nPerhaps there is something you have been carrying with regret: a choice, a pattern, a strained relationship, or a prayer you have avoided. You do not have to hide it from God. He already knows, and in Christ He receives those who return.\n\nReturning is not pretending the past did not matter. It is bringing the truth into the light of Jesus' mercy. He does not ask us to make ourselves worthy before we come near. He invites us to come honestly, to receive forgiveness, and to let His grace begin its work in us.\n\nTake a moment now to turn your heart toward Him. You may simply say, Lord Jesus, I return to You.\n\nWhatever has felt distant, unfinished, or ashamed in you, place it before Christ. His mercy is not reluctant. His welcome is not fragile. The One who calls us to return is the One who has opened the way for us to be received.\n\nAs you continue today, rest in this: Christ's mercy is real, and He receives those who return.", prayer: "Lord Jesus, receive us as we return to You. Amen.", journal: "What do you want to bring honestly before Christ today?", practice: "Take one unhurried moment to pray: “Lord Jesus, I return to You.”", notes: "Owner-supplied revised prayer text is not present in this local workspace; paste it here before approval.", rights: "Translation and quotation decision pending", narrationRights: false, versions: ["Version 2 — revised from owner feedback; ready for owner review", "Version 1 — ready for owner review"] },
  { id: "renewal-2", title: "Renewal Day 2 — Release", type: "Guided prayer", scripture: "1 Peter 5:7; Psalm 55:22", status: "owner_review", reflection: "Release is not denial. Some burdens are serious, and naming them before God is an act of honesty. Christ does not minimize what weighs on us; He invites us to bring it into His care.\n\nWe release what we cannot carry well, not because it no longer matters, but because Jesus is faithful and compassionate. Returning to prayer when a concern rises again is not failure. It is practising trust.", script: "Welcome to Strongr Daily.\n\nToday we bring what feels heavy into the care of Christ. First Peter 5:7 and Psalm 55:22 remind us that God welcomes the burdens we cannot carry alone.\n\nThere may be a concern that has followed you through the day: uncertainty about someone you love, a decision without a clear answer, grief, pressure, or a responsibility that feels beyond your strength. Christ does not ask you to make it seem smaller before you come to Him. He meets you with invitation and care.\n\nIn prayer, we can name the burden plainly. We can release the need to control every outcome. We can ask Jesus to hold what is beyond our reach and to guide us in what is ours to do.\n\nIf this concern returns later, you have not failed. Return to prayer again. Each return is a practice of trust: a way of placing the same real need in the faithful care of Christ.\n\nFor this moment, bring one burden before Him. Let your prayer be simple and true. Jesus, I place this in Your care.", prayer: "Faithful God, hold what is too heavy for me. Amen.", journal: "What burden do you need to place again in Christ's care?", practice: "Name one burden before Jesus, then pray: “I place this in Your care.”", notes: "Owner-supplied revised prayer text is not present in this local workspace; paste it here before approval.", rights: "Translation and quotation decision pending", narrationRights: false, versions: ["Version 2 — revised from owner feedback; ready for owner review", "Version 1 — ready for owner review"] },
  { id: "renewal-3", title: "Renewal Day 3 — Be Still", type: "Guided Scripture reflection", scripture: "Psalm 46:10; Isaiah 30:15", status: "owner_review", reflection: "Christian stillness is not empty attention. It is a quiet turning of the heart toward the God who is present and faithful.\n\nPsalm 46:10 and Isaiah 30:15 call us to remember who God is before we are consumed by what is urgent. In Christ, quiet becomes a place to receive His care and to attend to His Word.", script: "Welcome to Strongr Daily.\n\nThis is a guided Scripture reflection on Psalm 46:10 and Isaiah 30:15. We will not add Scripture wording here while its translation and quotation decision remains open. Instead, let these references direct your attention toward God.\n\nAs you breathe, receive each breath as a gift from the Lord. Let the quiet make room for this simple truth: Jesus Christ is near, and His care is steady.\n\nYou may have brought hurry, questions, or weariness into this moment. You do not need to force them away. Turn them toward God. Ask Him to gather your attention and to make you receptive to His presence.\n\nStillness before God is not withdrawal from life. It is a way of remembering that the Lord is God and that we belong to Him.\n\nRemain for a brief moment in prayer. Lord Jesus, keep my heart turned toward You.\n\nAs you return to your day, carry this quiet confidence: Christ is with you, and His faithfulness does not depend on your ability to hold everything together.", prayer: "God of peace, draw my attention to You. Amen.", journal: "Where do you need to turn your attention toward God today?", practice: "Set aside three minutes to sit before God and pray, “Lord Jesus, keep my heart turned toward You.”", notes: "Owner-supplied revised prayer text is not present in this local workspace; paste it here before approval.", rights: "Translation and quotation decision pending", narrationRights: false, versions: ["Version 2 — revised from owner feedback; ready for owner review", "Version 1 — ready for owner review"] },
];

const labels: Record<Status, string> = { draft: "Draft", owner_review: "Owner review", revision_requested: "Revision requested", owner_editing: "Owner editing", owner_edit_complete: "Owner edit complete", owner_approved: "Wording approved", narration_authorized: "Narration authorized", audio_generated: "Audio generated", audio_review: "Audio review", audio_accepted_private: "Private audio accepted", release_approved: "Release approved" };
const count = (value: string) => value.trim() ? value.trim().split(/\s+/).length : 0;

async function sha256(value: string) {
  const bytes = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

export function ContentReviewPage({ developmentPreview = false }: { readonly developmentPreview?: boolean }) {
  const [items, setItems] = useState<readonly Item[]>(seeds);
  const [selectedId, setSelectedId] = useState(seeds[1]!.id);
  const [notice, setNotice] = useState("Owner edits stay in Studio. Nothing is sent to a provider from this screen.");
  const item = items.find(({ id }) => id === selectedId) ?? items[0]!;
  const words = useMemo(() => count(item.script), [item.script]);
  const update = (patch: Partial<Item>) => setItems((current) => current.map((entry) => {
    if (entry.id !== item.id) return entry;
    const status = patch.status ?? (Object.hasOwn(patch, "script") && (entry.status === "owner_approved" || entry.status === "narration_authorized") ? "owner_editing" : entry.status);
    const next = { ...entry, ...patch, status } as Item;
    if (Object.hasOwn(patch, "script")) {
      const { lockedHash: _discarded, ...withoutLock } = next;
      return withoutLock;
    }
    return next;
  }));
  const mutate = (status: Status, message: string) => { update({ status }); setNotice(message); };
  const approve = async () => { const hash = await sha256(item.script); update({ status: "owner_approved", lockedHash: hash, versions: [`Version ${item.versions.length + 1} — immutable wording approval`, ...item.versions] }); setNotice("Wording approved for this exact version. The locked script is recorded in the Audit details."); };
  const authorize = () => mutate("narration_authorized", "Narration authorization is recorded for the locked wording only. No provider call was made.");
  const field = (label: string, key: keyof Pick<Item, "reflection" | "script" | "prayer" | "journal" | "practice" | "notes">, rows = 4) => <label>{label}<textarea onChange={(event) => update({ [key]: event.currentTarget.value })} rows={rows} value={item[key]} /></label>;

  return <div className="content-review-page">
    {developmentPreview ? <aside className="development-preview-banner" role="status"><strong>Development review mode</strong><span>Local seeded data only. This preview is not connected to Studio authentication, tenant data, providers, or production actions.</span></aside> : null}
    <div className="page-heading"><p className="eyebrow">Strongr Daily · Owner workspace</p><h1>Content review</h1><p>Review wording in one calm place. Sensitive actions stay unavailable until their required approvals are complete.</p></div>
    <p className="workflow-notice" role="status">{notice}</p>
    <div className="review-layout">
      <aside className="review-list" aria-label="Content items">{items.map((entry) => <button className={entry.id === item.id ? "is-selected" : ""} key={entry.id} onClick={() => setSelectedId(entry.id)} type="button"><strong>{entry.title}</strong><span>{labels[entry.status]}</span></button>)}</aside>
      <section className="review-editor">
        <header className="review-heading"><div><p className="eyebrow">{labels[item.status]}</p><h2>{item.title}</h2><p>{item.type} · {item.scripture}</p></div><span className="status-pill status-pill--warning">{item.rights}</span></header>
        <div className="review-metadata"><span>Last edited by Neil</span><span>Last edited today</span><span>{words} words · {item.script.length} characters · about {Math.max(1, Math.round(words / 130))} minutes</span></div>
        <div className="review-fields">{field("Written reflection", "reflection", 6)}{field("Narration script", "script", 10)}{field("Prayer", "prayer", 4)}{field("Journal prompt", "journal", 3)}{field("Daily Practice", "practice", 3)}{field("Owner notes", "notes", 3)}</div>
        <div className="review-actions"><button className="secondary-button" onClick={() => setNotice("Draft saved in this review session. No wording was changed.")} type="button">Save Draft</button><button className="secondary-button" onClick={() => mutate("revision_requested", "Revision requested. The wording remains editable.")} type="button">Request Revision</button><button className="secondary-button" onClick={() => mutate("owner_edit_complete", "Owner editing marked complete. Review the exact wording before approval.")} type="button">Mark Owner Edit Complete</button><button className="primary-button" disabled={item.status !== "owner_edit_complete"} onClick={() => void approve()} type="button">Approve Wording</button><button className="secondary-button" onClick={() => mutate("owner_editing", "Reopened for owner editing. Any prior wording lock is no longer valid.")} type="button">Reopen for Editing</button><button className="primary-button" disabled={item.status !== "owner_approved" || !item.narrationRights} onClick={authorize} type="button">Authorize ElevenLabs</button><button className="danger-button" disabled={item.status !== "narration_authorized"} onClick={() => mutate("owner_approved", "Narration authorization revoked. No provider call was made.")} type="button">Revoke Narration Authorization</button></div>
        <section className="audio-review"><h3>Private audio review</h3><p>Audio is not connected in this phase. Private audio acceptance will never release content.</p><div className="audio-placeholder">Audio player placeholder</div><dl><div><dt>Duration</dt><dd>Not generated</dd></div><div><dt>Voice</dt><dd>Not selected</dd></div><div><dt>Model</dt><dd>Not connected</dd></div><div><dt>Script lock</dt><dd>{item.lockedHash ? "Approved wording locked" : "Not yet locked"}</dd></div><div><dt>Credits</dt><dd>None used</dd></div></dl><div className="review-actions"><button className="secondary-button" disabled type="button">Review Audio</button><button className="secondary-button" disabled type="button">Accept Private Audio</button><button className="danger-button" disabled type="button">Reject Audio</button><button className="secondary-button" disabled type="button">Request One Revision</button></div></section>
        <section className="status-timeline"><h3>Status timeline</h3><ol>{["draft", "owner_review", "owner_editing", "owner_edit_complete", "owner_approved", "narration_authorized", "audio_review", "audio_accepted_private", "release_approved"].map((status) => <li className={status === item.status ? "current" : ""} key={status}>{labels[status as Status]}</li>)}</ol></section>
        <details className="advanced-details"><summary>Details and audit</summary><p>Version history: {item.versions.join(" · ")}</p><p>Script SHA-256: {item.lockedHash ?? "Created only after wording approval"}</p><p>Tenant isolation, owner permissions, MFA/AAL2, approval evidence, audit history, and service-role boundaries remain enforced by the existing governed workflow.</p></details>
      </section>
    </div>
  </div>;
}
